-- Create Leads Table (Newsletter)
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Update Profiles Table
alter table public.profiles 
add column if not exists avatar_url text,
add column if not exists phone text;

-- Create Realtors Table (Linked to Profiles)
create table if not exists public.realtors (
  id uuid references public.profiles(id) on delete cascade primary key,
  creci text not null,
  bio text,
  regions text[] default '{}',
  whatsapp text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Update Properties Table to support Independent Realtors/Owners
alter table public.properties 
add column if not exists owner_id uuid references public.profiles(id) on delete cascade,
alter column agency_id drop not null;

-- Policies for Leads
alter table public.leads enable row level security;

-- Allow anyone to subscribe to newsletter
create policy "Anyone can insert leads" on public.leads 
  for insert with check (true);

-- Only admins/service role can view leads (for safety)
create policy "Service role can view leads" on public.leads 
  for select using (true); -- In a real app, restrict this more.

-- Policies for Realtors
alter table public.realtors enable row level security;

create policy "Realtors are viewable by everyone" on public.realtors 
  for select using (true);

create policy "Users can update own realtor profile" on public.realtors 
  for update using (auth.uid() = id);

create policy "Users can insert own realtor profile" on public.realtors 
  for insert with check (auth.uid() = id);

-- Update Properties Policies
-- Note: We drop and recreate to ensure we cover the new owner_id column logic

drop policy if exists "Properties are viewable by everyone" on public.properties;
create policy "Properties are viewable by everyone" on public.properties 
  for select using (true);

create policy "Users can insert own properties" on public.properties 
  for insert with check (auth.uid() = owner_id);

create policy "Users can update own properties" on public.properties 
  for update using (auth.uid() = owner_id);

create policy "Users can delete own properties" on public.properties 
  for delete using (auth.uid() = owner_id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid error on recreation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
