-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Agencies Table
create table public.agencies (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  email text,
  description text,
  logo_url text,
  creci text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Properties Table
create table public.properties (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  description text,
  price numeric not null,
  location text not null,
  bedrooms integer default 0,
  bathrooms integer default 0,
  area numeric default 0,
  type text check (type in ('Venda', 'Aluguel')),
  features text[] default '{}',
  images text[] default '{}',
  featured boolean default false,
  agency_id bigint references public.agencies(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Profiles Table (extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Favorites Table
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  property_id uuid references public.properties(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, property_id)
);

-- Enable Row Level Security (RLS)
alter table public.agencies enable row level security;
alter table public.properties enable row level security;
alter table public.profiles enable row level security;
alter table public.favorites enable row level security;

-- Policies (Security Rules)

-- Agencies: Everyone can read, only admins can update
create policy "Agencies are viewable by everyone" on public.agencies
  for select using (true);

-- Properties: Everyone can read, only admins can update
create policy "Properties are viewable by everyone" on public.properties
  for select using (true);

-- Profiles: Users can read/update their own profile
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

-- Favorites: Users can read/create/delete their own favorites
create policy "Users can view own favorites" on public.favorites
  for select using (auth.uid() = user_id);

create policy "Users can add favorites" on public.favorites
  for insert with check (auth.uid() = user_id);

create policy "Users can remove favorites" on public.favorites
  for delete using (auth.uid() = user_id);
